apiVersion: apps/v1
kind: Deployment
metadata:
  name: book
  labels:
    app: webdeploy
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 5
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: booklibrary:1.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
